import 'package:shared_preferences/shared_preferences.dart';

class AppStrings {
  static String currentLang = 'en';

  static Map<String, Map<String, String>> _data = {
    'en': {
      'profile': 'Profile',
      'export_backup': 'Export Backup',
      'import_backup': 'Import Backup',
      'privacy': 'Privacy Policy',
      'support': 'Support',
      'about': 'About App',
      'logout': 'Logout',
      'rate_app': 'Rate App',
      'members': 'Members',
      'expense': 'Expense',
      'recent_expenses': 'Recent Expenses',
      'total': 'Total',
      'deposit': 'Deposit',
      'view_report': 'View Report',
      'edit': 'Edit',
      'delete': 'Delete',
      'add_member_details': 'Add Member Details',
      'name': 'Name',
      'mobile': 'Mobile',
      'email': 'Email',
      'pay_amount': 'Pay Amount',
      'pay': 'Pay',
      'admin_marked': 'Admin already marked',
      'add_member': 'Add Member',
      'all_members': 'All Members',
      'ledger': 'Ledger',
      'current_balance': 'Current Balance',
      'amount': 'Amount',
      'note': 'Note',
      'withdraw': 'Withdraw',
      'add_entry': 'Add Entry',
      'transactions': 'Transactions',
      'new_trip': 'New Trip / Group',
      'title': 'Name / Title',
      'description': 'Description',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'save': 'Save',
      'saving': 'Saving...',
      'create_trip': 'Create Trip / Group',
      'expense_date': 'Expense Date',
      'from': 'From',
      'to': 'To',
      'category': 'Category',
      'select_members': 'Select Members',
      'select_all': 'Select All',
      'add_category': 'Add Category',
      'enter_category': 'Enter Category Name',
      'cancel': 'Cancel',
      'add': 'Add',
      'pdf': 'PDF',
      'member_expense_details': 'Member Expense Details',
      'person': 'Person',
      'spent': 'Spent',
      'share': 'Share',
      'balance': 'Balance',
      'expense_list': 'Expense List',
      'view_settlement': 'View Settlement',
      'add_expense': 'Add Expense',
      'add_expense_details': 'Add Expense Details', // English
      'enter_valid_amount': 'Enter valid amount',
      'amount_positive': 'Amount must be greater than 0',
      'entry_added': 'Entry added successfully',
      'edit_expense': 'Edit Expense',
      'update_expense': 'Update Expense',
      'pdf_downloaded': 'PDF downloaded successfully!',
      'expense_deleted': 'Expense deleted',
      'expense_updated': 'Expense updated',
      'select_members_first': 'Select members first!',
      'name_required': 'Name is required!',
      'pay_amount_required': 'Pay Amount is required!',
      'valid_pay_amount': 'Enter valid Pay Amount!',
      'member_saved': 'Member saved!',
      'expense_added': 'Expense added successfully!',
      'fill_required': 'Please fill all required fields',
      'select_date': 'Please select expense date',
      'backup_exported': 'Backup exported successfully',
      'backup_restored': 'Backup restored. Refreshing...',
      'added_success': 'Added successfully!',
      'valid_mobile': 'Enter valid 10 digit mobile number',
      'profile_updated': 'Profile updated successfully!',
      'address': 'Address',
      'admin': 'Admin',
      "appearance": "Appearance",
      "theme": "Theme",
      "language": "Language",
      "backup_completed": "Backup completed successfully",
      "restore_completed": "Backup restored successfully",
      "no_backup_found": "No backup found in your Google Drive",
      "backup_failed": "Backup failed. Please try again",
      "system": "System",
      "dark": "Dark",
      "light": "Light",
      "customize_experience": "Customize your app experience",
      'ok': 'OK',
      "backup_restore": "Backup & Restore",
      "google_account": "Google Account",
      "not_connected": "Not connected",
      "change": "Switch",
      "auto_backup": "Auto Backup",
      "on": "On",
      "off": "Off",
      "backup_frequency": "Backup frequency",
      "daily": "Daily",
      "weekly": "Weekly",
      "monthly": "Monthly",
      "backup_now": "Backup Now",
      "restore_backup": "Restore Backup",
      "settlement_title": "Settlement",
      "no_settlement": "No settlement required",
      "gives_money": "{from} has to give ₹{amount} to {to}",
      "analytics": "Analytics",
      "trips": "Trips",
      "confirm_restore": "Restore Backup?",
      "restore_warning":
          "All your current data will be deleted and replaced with backup data.",
      "restore": "Restore",
      "downloading_backup": "Downloading backup...",
      "restoring_data": "Restoring data...",
      "completed": "Completed",
      "no_data_backup": "No data available to backup",
    },

    'hi': {
      'profile': 'प्रोफ़ाइल',
      'export_backup': 'बैकअप निर्यात करें',
      'import_backup': 'बैकअप आयात करें',
      'privacy': 'गोपनीयता नीति',
      'support': 'सहायता',
      'about': 'ऐप के बारे में',
      'logout': 'लॉगआउट',
      'rate_app': 'ऐप को रेट करें',
      'members': 'सदस्य',
      'expense': 'खर्च',
      'add_expense_details': 'खर्च का विवरण जोड़ें',
      'recent_expenses': 'हाल ही के खर्च',
      'total': 'कुल',
      'deposit': 'जमा राशि',
      'view_report': 'रिपोर्ट देखें',
      'edit': 'संपादित करें',
      'delete': 'हटाएं',
      'add_member_details': 'सदस्य की जानकारी जोड़ें',
      'name': 'नाम',
      'mobile': 'मोबाइल',
      'email': 'ईमेल',
      'pay_amount': 'भुगतान राशि',
      'pay': 'भुगतान',
      'admin_marked': 'एडमिन पहले से चुना गया',
      'add_member': 'सदस्य जोड़ें',
      'all_members': 'सभी सदस्य',
      'ledger': 'हिसाब किताब',
      'current_balance': 'वर्तमान बकाया',
      'amount': 'राशि',
      'note': 'नोट',
      'withdraw': 'पैसे निकालें',
      'add_entry': 'एंट्री करें',
      'transactions': 'लेन-देन',
      'new_trip': 'नया ग्रुप / ट्रिप',
      'title': 'नाम / शीर्षक',
      'description': 'विवरण',
      'start_date': 'प्रारंभ तिथि',
      'end_date': 'समाप्ति तिथि',
      'save': 'सहेजें',
      'saving': 'सेव हो रहा है...',
      'create_trip': 'ग्रुप बनाएं',
      'expense_date': 'खर्च की तारीख',
      'from': 'से',
      'to': 'तक',
      'category': 'श्रेणी',
      'select_members': 'सदस्य चुनें',
      'select_all': 'सभी चुनें',
      'add_category': 'श्रेणी जोड़ें',
      'enter_category': 'श्रेणी का नाम दर्ज करें',
      'cancel': 'रद्द करें',
      'add': 'जोड़ें',
      'pdf': 'पीडीएफ',
      'member_expense_details': 'सदस्यों का खर्च विवरण',
      'person': 'व्यक्ति',
      'spent': 'खर्च किया',
      'share': 'हिस्सा',
      'balance': 'बकाया',
      'expense_list': 'खर्चों की सूची',
      'view_settlement': 'हिसाब देखें',
      'add_expense': 'खर्च जोड़ें',
      'enter_valid_amount': 'मान्य राशि दर्ज करें',
      'amount_positive': 'राशि 0 से अधिक होनी चाहिए',
      'entry_added': 'एंट्री सफलतापूर्वक जोड़ी गई',
      'edit_expense': 'खर्च संपादित करें',
      'update_expense': 'खर्च अपडेट करें',
      'pdf_downloaded': 'पीडीएफ सफलतापूर्वक डाउनलोड हो गया!',
      'expense_deleted': 'खर्च हटाया गया',
      'expense_updated': 'खर्च अपडेट किया गया',
      'select_members_first': 'पहले सदस्य चुनें!',
      'name_required': 'नाम आवश्यक है!',
      'pay_amount_required': 'भुगतान राशि आवश्यक है!',
      'valid_pay_amount': 'मान्य भुगतान राशि दर्ज करें!',
      'member_saved': 'सदस्य सफलतापूर्वक सहेजा गया!',
      'expense_added': 'खर्च सफलतापूर्वक जोड़ा गया!',
      'fill_required': 'कृपया सभी आवश्यक फ़ील्ड भरें',
      'select_date': 'कृपया खर्च की तारीख चुनें',
      'backup_exported': 'बैकअप सफलतापूर्वक निर्यात किया गया',
      'backup_restored': 'बैकअप बहाल किया गया। रीफ़्रेश हो रहा है...',
      'added_success': 'सफलतापूर्वक जोड़ा गया!',
      'valid_mobile': 'मान्य 10 अंकों का मोबाइल नंबर दर्ज करें',
      'profile_updated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गया!',
      'address': 'पता',
      'admin': 'एडमिन',
      "appearance": "दिखावट",
      "theme": "थीम",
      "language": "भाषा",
      "system": "सिस्टम",
      "dark": "डार्क",
      "light": "लाइट",
      "customize_experience": "अपने ऐप अनुभव को अनुकूलित करें",
      'ok': 'ठीक है',
      "backup_completed": "बैकअप सफलतापूर्वक पूरा हुआ",
      "restore_completed": "बैकअप सफलतापूर्वक पुनर्स्थापित हुआ",
      "no_backup_found": "आपके Google Drive में कोई बैकअप नहीं मिला",
      "backup_failed": "बैकअप असफल रहा। कृपया दोबारा प्रयास करें",
      "backup_restore": "बैकअप और पुनर्स्थापना",
      "google_account": "गूगल अकाउंट",
      "not_connected": "कनेक्ट नहीं है",
      "change": "बदलें",
      "auto_backup": "ऑटो बैकअप",
      "on": "चालू",
      "off": "बंद",
      "backup_frequency": "बैकअप की आवृत्ति",
      "daily": "प्रतिदिन",
      "weekly": "साप्ताहिक",
      "monthly": "मासिक",
      "backup_now": "अभी बैकअप लें",
      "restore_backup": "बैकअप पुनर्स्थापित करें",
      "settlement_title": "सेटलमेंट",
      "no_settlement": "कोई सेटलमेंट नहीं है",
      "gives_money": "{from} को {to} को ₹{amount} देने हैं",
      "analytics": "एनालिटिक्स",
      "trips": "ट्रिप्स",
      "confirm_restore": "बैकअप रिस्टोर करें?",
      "restore_warning":"आपका मौजूदा सारा डेटा हट जाएगा और बैकअप से नया डेटा आ जाएगा।",
      "no_data_backup": "बैकअप के लिए कोई डेटा उपलब्ध नहीं है",
    },

    'pa': {
      'profile': 'ਪ੍ਰੋਫਾਈਲ',
      'export_backup': 'ਬੈਕਅੱਪ ਐਕਸਪੋਰਟ ਕਰੋ',
      'import_backup': 'ਬੈਕਅੱਪ ਇੰਪੋਰਟ ਕਰੋ',
      'privacy': 'ਪਰਾਈਵੇਸੀ ਨੀਤੀ',
      'support': 'ਸਹਾਇਤਾ',
      'about': 'ਐਪ ਬਾਰੇ',
      'logout': 'ਲੌਗਆਉਟ',
      'rate_app': 'ਰੇਟ ਕਰੋ',
      'members': 'ਮੈਂਬਰ',
      'expense': 'ਖਰਚਾ',
      'add_expense_details': 'ਖਰਚਾ ਵੇਰਵਾ ਜੋੜੋ',
      'recent_expenses': 'ਤਾਜ਼ਾ ਖਰਚੇ',
      'total': 'ਕੁੱਲ',
      'deposit': 'ਜਮ੍ਹਾਂ',
      'view_report': 'ਰਿਪੋਰਟ ਵੇਖੋ',
      'edit': 'ਸੋਧੋ',
      'delete': 'ਹਟਾਓ',
      'add_member_details': 'ਮੈਂਬਰ ਦੀ ਜਾਣਕਾਰੀ ਜੋੜੋ',
      'name': 'ਨਾਮ',
      'mobile': 'ਮੋਬਾਈਲ',
      'email': 'ਈਮੇਲ',
      'pay_amount': 'ਭੁਗਤਾਨ ਰਕਮ',
      'pay': 'ਭੁਗਤਾਨ',
      'admin_marked': 'ਐਡਮਿਨ ਪਹਿਲਾਂ ਹੀ ਚੁਣਿਆ ਗਿਆ',
      'add_member': 'ਮੈਂਬਰ ਜੋੜੋ',
      'all_members': 'ਸਾਰੇ ਮੈਂਬਰ',
      'ledger': 'ਹਿਸਾਬ ਕਿਤਾਬ',
      'current_balance': 'ਮੌਜੂਦਾ ਬਕਾਇਆ',
      'amount': 'ਰਕਮ',
      'note': 'ਨੋਟ',
      'withdraw': 'ਪੈਸੇ ਕੱਢੋ',
      'add_entry': 'ਐਂਟਰੀ ਕਰੋ',
      'transactions': 'ਲੈਣ-ਦੇਣ',
      'new_trip': 'ਨਵਾਂ ਗਰੁੱਪ / ਟ੍ਰਿਪ',
      'title': 'ਨਾਮ / ਸਿਰਲੇਖ',
      'description': 'ਵੇਰਵਾ',
      'start_date': 'ਸ਼ੁਰੂ ਮਿਤੀ',
      'end_date': 'ਅੰਤ ਮਿਤੀ',
      'save': 'ਸੇਵ ਕਰੋ',
      'saving': 'ਸੇਵ ਹੋ ਰਿਹਾ ਹੈ...',
      'create_trip': 'ਗਰੁੱਪ ਬਣਾਓ',
      'expense_date': 'ਖਰਚ ਦੀ ਤਾਰੀਖ',
      'from': 'ਤੋਂ',
      'to': 'ਤੱਕ',
      'category': 'ਸ਼੍ਰੇਣੀ',
      'select_members': 'ਮੈਂਬਰ ਚੁਣੋ',
      'select_all': 'ਸਭ ਚੁਣੋ',
      'add_category': 'ਸ਼੍ਰੇਣੀ ਜੋੜੋ',
      'enter_category': 'ਸ਼੍ਰੇਣੀ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'add': 'ਜੋੜੋ',
      'pdf': 'ਪੀਡੀਐਫ',
      'member_expense_details': 'ਮੈਂਬਰਾਂ ਦਾ ਖਰਚਾ ਵੇਰਵਾ',
      'person': 'ਵਿਅਕਤੀ',
      'spent': 'ਖਰਚਿਆ',
      'share': 'ਹਿੱਸਾ',
      'balance': 'ਬਕਾਇਆ',
      'expense_list': 'ਖਰਚਿਆਂ ਦੀ ਸੂਚੀ',
      'view_settlement': 'ਹਿਸਾਬ ਵੇਖੋ',
      'add_expense': 'ਖਰਚਾ ਜੋੜੋ',
      'enter_valid_amount': 'ਸਹੀ ਰਕਮ ਦਰਜ ਕਰੋ',
      'amount_positive': 'ਰਕਮ 0 ਤੋਂ ਵੱਧ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ',
      'entry_added': 'ਐਂਟਰੀ ਸਫਲਤਾਪੂਰਵਕ ਜੋੜੀ ਗਈ',
      'edit_expense': 'ਖਰਚਾ ਸੋਧੋ',
      'update_expense': 'ਖਰਚਾ ਅਪਡੇਟ ਕਰੋ',
      'pdf_downloaded': 'ਪੀਡੀਐਫ ਸਫਲਤਾਪੂਰਵਕ ਡਾਊਨਲੋਡ ਹੋ ਗਿਆ!',
      'expense_deleted': 'ਖਰਚਾ ਹਟਾਇਆ ਗਿਆ',
      'expense_updated': 'ਖਰਚਾ ਅਪਡੇਟ ਹੋ ਗਿਆ',
      'select_members_first': 'ਪਹਿਲਾਂ ਮੈਂਬਰ ਚੁਣੋ!',
      'name_required': 'ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ!',
      'pay_amount_required': 'ਭੁਗਤਾਨ ਰਕਮ ਲਾਜ਼ਮੀ ਹੈ!',
      'valid_pay_amount': 'ਸਹੀ ਭੁਗਤਾਨ ਰਕਮ ਦਰਜ ਕਰੋ!',
      'member_saved': 'ਮੈਂਬਰ ਸਫਲਤਾਪੂਰਵਕ ਸੇਵ ਹੋ ਗਿਆ!',
      'expense_added': 'ਖਰਚਾ ਸਫਲਤਾਪੂਰਵਕ ਜੋੜਿਆ ਗਿਆ!',
      'fill_required': 'ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਲਾਜ਼ਮੀ ਫੀਲਡ ਭਰੋ',
      'select_date': 'ਕਿਰਪਾ ਕਰਕੇ ਖਰਚ ਦੀ ਤਾਰੀਖ ਚੁਣੋ',
      'backup_exported': 'ਬੈਕਅੱਪ ਸਫਲਤਾਪੂਰਵਕ ਐਕਸਪੋਰਟ ਹੋ ਗਿਆ',
      'backup_restored': 'ਬੈਕਅੱਪ ਰੀਸਟੋਰ ਹੋ ਗਿਆ। ਰੀਫ੍ਰੈਸ਼ ਹੋ ਰਿਹਾ ਹੈ...',
      'added_success': 'ਸਫਲਤਾਪੂਰਵਕ ਜੋੜਿਆ ਗਿਆ!',
      'valid_mobile': 'ਸਹੀ 10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
      'profile_updated': 'ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅਪਡੇਟ ਹੋ ਗਈ!',
      'address': 'ਪਤਾ',
      'admin': 'ਐਡਮਿਨ',
      "appearance": "ਦਿੱਖ",
      "theme": "ਥੀਮ",
      "language": "ਭਾਸ਼ਾ",
      "system": "ਸਿਸਟਮ",
      "dark": "ਡਾਰਕ",
      "light": "ਲਾਈਟ",
      "customize_experience": "ਆਪਣਾ ਐਪ ਅਨੁਭਵ ਕਸਟਮਾਈਜ਼ ਕਰੋ",
      'ok': 'ਠੀਕ ਹੈ',
      "backup_completed": "ਬੈਕਅੱਪ ਸਫਲਤਾਪੂਰਵਕ ਪੂਰਾ ਹੋ ਗਿਆ",
      "restore_completed": "ਬੈਕਅੱਪ ਸਫਲਤਾਪੂਰਵਕ ਰੀਸਟੋਰ ਹੋ ਗਿਆ",
      "no_backup_found": "ਤੁਹਾਡੇ Google Drive ਵਿੱਚ ਕੋਈ ਬੈਕਅੱਪ ਨਹੀਂ ਮਿਲਿਆ",
      "backup_failed": "ਬੈਕਅੱਪ ਫੇਲ ਹੋ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
      "backup_restore": "ਬੈਕਅੱਪ ਅਤੇ ਰੀਸਟੋਰ",
      "google_account": "ਗੂਗਲ ਅਕਾਊਂਟ",
      "not_connected": "ਕਨੈਕਟ ਨਹੀਂ ਹੈ",
      "change": "ਬਦਲੋ",
      "auto_backup": "ਆਟੋ ਬੈਕਅੱਪ",
      "on": "ਚਾਲੂ",
      "off": "ਬੰਦ",
      "backup_frequency": "ਬੈਕਅੱਪ ਦੀ ਫ੍ਰਿਕਵੈਂਸੀ",
      "daily": "ਰੋਜ਼ਾਨਾ",
      "weekly": "ਹਫਤਾਵਾਰ",
      "monthly": "ਮਹੀਨਾਵਾਰ",
      "backup_now": "ਹੁਣੇ ਬੈਕਅੱਪ ਕਰੋ",
      "restore_backup": "ਬੈਕਅੱਪ ਰੀਸਟੋਰ ਕਰੋ",
      "settlement_title": "ਹਿਸਾਬ",
      "no_settlement": "ਕੋਈ ਹਿਸਾਬ ਨਹੀਂ",
      "gives_money": "{from} ਨੇ ₹{amount} {to} ਨੂੰ ਦੇਣੇ ਆ",
      "analytics": "ਐਨਾਲਿਟਿਕਸ",
      "trips": "ਟ੍ਰਿਪਸ",
      "confirm_restore": "ਬੈਕਅਪ ਰੀਸਟੋਰ ਕਰੀਏ?",
      "restore_warning":
          "ਤੁਹਾਡਾ ਸਾਰਾ ਮੌਜੂਦਾ ਡਾਟਾ ਮਿਟ ਜਾਵੇਗਾ ਅਤੇ ਬੈਕਅਪ ਤੋਂ ਨਵਾਂ ਡਾਟਾ ਆ ਜਾਵੇਗਾ।",
      "no_data_backup": "ਬੈਕਅਪ ਲਈ ਕੋਈ ਡਾਟਾ ਮੌਜੂਦ ਨਹੀਂ ਹੈ",
    },
  };

  static String get(String key) {
    return _data[currentLang]?[key] ?? key;
  }

  static Future<void> setLang(String lang) async {
    final prefs = await SharedPreferences.getInstance();
    currentLang = lang;
    await prefs.setString('lang', lang);
  }

  static Future<void> loadLang() async {
    final prefs = await SharedPreferences.getInstance();
    currentLang = prefs.getString('lang') ?? 'en';
  }
}
